Add production and dev db url
gpbPiazza/API-Codify pull request #10
Opened 2021-02-08 20:13 UTC by gpbPiazza

2021-02-08 20:16 UTC, thiagoribb approved these changes

2021-02-08 20:41 UTC, thiagoribb approved these changes

2021-02-09 16:33 UTC, vagnerpavani requested changes

2021-02-09 16:33 UTC, vagnerpavani commented on tests/unitary/controllers/sessionController.test.js
>  /* eslint-disable no-undef */
Pessoal, tem vários arquivos com exceção a alguma regra do ESlint. Vale a pena evitarmos isso ao máximo, o Eslint que ajuda a manter o projeto padronizado.

2021-02-09 16:33 UTC, vagnerpavani commented on tests/unitary/controllers/sessionController.test.js
O nome de pasta unitary não é muito comum no mercado. Vale a pena trocar o nome para unit por exemplo.

2021-02-09 16:34 UTC, gpbPiazza commented on tests/unitary/controllers/sessionController.test.js
ok

2021-02-09 16:39 UTC, gpbPiazza commented on tests/unitary/controllers/sessionController.test.js
>  /* eslint-disable no-undef */
Concordo vagner mas, está regra do eslint está sendo desligada pois o eslint não aceita que escrevemos `decribe`, `it` e `jest.mock` se termos definido eles, como poderiamos seguir a regra nestes casos? 

E acredito que é ok desligar espeificamente alguma regra por arquivo, pois está regra pode ser util nos outros arquivos do projeto.

2021-02-09 19:39 UTC, vagnerpavani approved these changes

2021-02-09 19:39 UTC, merged