Start course route
gpbPiazza/API-Codify pull request #11
Opened 2021-02-08 22:56 UTC by gpbPiazza

2021-02-08 23:23 UTC, thiagoribb approved these changes

2021-02-09 17:26 UTC, vagnerpavani requested changes

2021-02-09 17:26 UTC, vagnerpavani commented on src/routers/coursesRouter.js
> +    return res.status(500).send({ error: 'call the responsible person, routeError: /api/v1/courses/start ' });
Esse erro vale a pena enviar apenas o status, porque o front não vai usar essa mensagem.

2021-02-09 17:26 UTC, vagnerpavani commented on tests/unitary/controllers/coursesController.test.js
A mesma questão do nome unitary sinalizado no ultimo PR.

2021-02-09 19:27 UTC, gpbPiazza commented on src/routers/coursesRouter.js
> +    return res.status(500).send({ error: 'call the responsible person, routeError: /api/v1/courses/start ' });
Não é interessante ter essa mensagem para resolver um bug de forma mais rápida ?

2021-02-09 19:56 UTC, merged