Get all courses that i not started
gpbPiazza/API-Codify pull request #13
Opened 2021-02-11 18:55 UTC by gpbPiazza

2021-02-11 19:48 UTC, vagnerpavani requested changes

2021-02-11 19:48 UTC, vagnerpavani commented on src/middlewares/authenticationMiddleware.js
> +    console.log(execption, 'aaaaaaaaaaaaaaaaaaaaa');
Esse console.log() pode sair do código kkk ou mudar a mensagem nele.

2021-02-11 19:48 UTC, vagnerpavani commented on src/routers/coursesRouter.js
> +    console.log(e, 'aaaaaaaaaaaaaaaaaaaa');
Esse pode sair também, ou trocar a mensagem.

2021-02-11 22:12 UTC, thiagoribb approved these changes

2021-02-12 15:52 UTC, vagnerpavani approved these changes

2021-02-12 15:52 UTC, merged