Feature/adminBackEnd
gpbPiazza/API-Codify pull request #14
Opened 2021-02-11 22:01 UTC by herickmotta

2021-02-11 22:29 UTC, gpbPiazza approved these changes

2021-02-12 15:56 UTC, vagnerpavani requested changes

2021-02-12 15:56 UTC, vagnerpavani commented on src/routers/adminRouter/exercisesAdminRouter.js
> +  // if (error) return res.status(422).send({ error: error.details[0].message });
Esse comentário pode ser apagado.

2021-02-12 16:19 UTC, vagnerpavani approved these changes

2021-02-12 16:19 UTC, merged