Log in route
gpbPiazza/API-Codify pull request #2
Opened 2021-02-02 21:05 UTC by gpbPiazza

2021-02-02 22:53 UTC, vagnerpavani requested changes

2021-02-02 22:53 UTC, vagnerpavani commented on src/controllers/sessionController.js
> +}
Essa controller de session ainda esta usando uuid. Precisa seguir a restrição técnica de usar JWT.

2021-02-02 22:53 UTC, vagnerpavani commented on tests/unitary/controllers/authController.test.js
> +  it('Should retunr the user with password valid', async () => {
Ficou um errinho de digitação no return, acabou saindo retunr.

2021-02-02 23:00 UTC, gpbPiazza commented on src/controllers/sessionController.js
> +}
Próximo pull request está implementando JWT

2021-02-02 23:03 UTC, herickmotta commented on tests/unitary/controllers/authController.test.js
> +      password: 'hased_password',
seria "hashed_password" ?

2021-02-02 23:03 UTC, herickmotta approved these changes

2021-02-03 00:35 UTC, merged

2021-02-03 00:36 UTC, gpbPiazza commented on tests/unitary/controllers/authController.test.js
> +      password: 'hased_password',
boa boa, irei corrigir

2021-02-03 00:36 UTC, gpbPiazza commented on tests/unitary/controllers/authController.test.js
> +  it('Should retunr the user with password valid', async () => {
corrigindo